# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Add_Sets_LayersDialog
                                 A QGIS plugin
 Add Sets of Layers for facilily consolidation of potential map
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-14
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Code4Construct
        email                : ubonira@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import QRegExp
from qgis.PyQt.QtGui import QRegExpValidator
from qgis.PyQt.QtWidgets import QCheckBox, QHBoxLayout, QLabel, QLineEdit, QVBoxLayout

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'add_sets_layers_dialog_base.ui'))


class Add_Sets_LayersDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(Add_Sets_LayersDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.setWindowTitle('Add Sets of Layers')
        self._replace_preview_with_group_choices()

    def selected_group_keys(self):
        selected = [
            checkbox.property('group_key')
            for checkbox in self.group_checkboxes
            if checkbox.isChecked()
        ]
        return selected or ['group1']

    def area_filter_values(self):
        min_text = self.area_min_edit.text().strip()
        max_text = self.area_max_edit.text().strip()
        return {
            'min': int(min_text) if self.area_min_checkbox.isChecked() and min_text else None,
            'max': int(max_text) if self.area_max_checkbox.isChecked() and max_text else None,
        }

    def _replace_preview_with_group_choices(self):
        self.group_checkboxes = []
        choices = [
            (
                'group1',
                '一般施設_賃借施設',
                '一般施設と賃借施設を築年数別に作成します。',
            ),
            (
                'group2',
                '複合化可能一般施設_賃借施設',
                '複合化可能な一般施設と賃借施設だけを築年数別に作成します。',
            ),
            (
                'group3',
                '複合化可能一般施設_賃借施設_選択区外を除外',
                '選択区内は表示し、区外は7用途施設や消防署などを除外して作成します。',
            ),
        ]

        container = QtWidgets.QWidget(self)
        layout = QVBoxLayout(container)
        layout.setContentsMargins(8, 8, 8, 8)
        layout.setSpacing(8)

        heading = QLabel('作成するレイヤグループを選択してください。')
        heading.setWordWrap(True)
        layout.addWidget(heading)

        for index, (key, title, description) in enumerate(choices):
            checkbox = QCheckBox(title)
            checkbox.setProperty('group_key', key)
            checkbox.setToolTip(description)
            if index == 0:
                checkbox.setChecked(True)
            self.group_checkboxes.append(checkbox)
            layout.addWidget(checkbox)

            detail = QLabel(description)
            detail.setWordWrap(True)
            detail.setStyleSheet('color: #555; margin-left: 22px;')
            layout.addWidget(detail)

        area_title = QLabel('面積で絞り込む')
        area_title.setStyleSheet('margin-top: 14px; font-weight: 600;')
        layout.addWidget(area_title)

        area_layout = QHBoxLayout()
        area_layout.setContentsMargins(0, 0, 0, 0)
        self.area_min_checkbox = QCheckBox('')
        self.area_min_checkbox.toggled.connect(self._toggle_area_min_filter)
        area_layout.addWidget(self.area_min_checkbox)

        self.area_min_edit = self._create_area_edit()
        area_layout.addWidget(self.area_min_edit)
        area_layout.addWidget(QLabel('㎡ 以上'))

        self.area_max_checkbox = QCheckBox('')
        self.area_max_checkbox.toggled.connect(self._toggle_area_max_filter)
        area_layout.addWidget(self.area_max_checkbox)

        self.area_max_edit = self._create_area_edit()
        area_layout.addWidget(self.area_max_edit)
        area_layout.addWidget(QLabel('㎡ 未満'))
        area_layout.addStretch(1)
        layout.addLayout(area_layout)

        layout.addStretch(1)

        for widget_name in ('textBrowser', 'label', 'label_2'):
            widget = getattr(self, widget_name, None)
            if widget is not None:
                widget.hide()

        base_layout = self.layout()
        if base_layout is not None:
            base_layout.insertWidget(1, container)

    def _create_area_edit(self):
        edit = QLineEdit()
        edit.setEnabled(False)
        edit.setValidator(QRegExpValidator(QRegExp(r'[0-9]*'), self))
        edit.setFixedWidth(110)
        return edit

    def _toggle_area_min_filter(self, enabled):
        self.area_min_edit.setEnabled(enabled)
        if enabled:
            self.area_min_edit.setFocus()

    def _toggle_area_max_filter(self, enabled):
        self.area_max_edit.setEnabled(enabled)
        if enabled:
            self.area_max_edit.setFocus()
