# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MergePointFeaturesInPoligon
                                 A QGIS plugin
 Merge Point Features in the Poligon
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-29
        git sha              : $Format:%H$
        copyright            : (C) 2026 by code4construct
        email                : ubonira@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox

# Initialize Qt resources from file resources.py
from .resources import *
import os.path
from . import merge_visible_points_in_selected_polygon
import importlib

class MergePointFeaturesInPoligon:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'MergePointFeaturesInPoligon_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Merge Point Features in the Poligon')

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('MergePointFeaturesInPoligon', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/merge_point_features_in_poligon/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Merge Point Features in Poligon'),
            callback=self.run,
            parent=self.iface.mainWindow())


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Merge Point Features in the Poligon'),
                action)
            self.iface.removeToolBarIcon(action)

    def show_plugin_description(self):
        """Show a short explanation before the plugin workflow starts."""
        select_image_path = os.path.join(
            self.plugin_dir,
            'images',
            'select.png'
        ).replace(os.sep, '/')

        QMessageBox.information(
            self.iface.mainWindow(),
            self.tr(u'Merge Point Features in Poligon'),
            self.tr(
                u'<p>このプラグインは、選択したポリゴン内にある表示中のポイント地物を抽出し、'
                u'1つのGeoPackageレイヤとして保存します。</p>'
                u'<p><b>使い方:</b></p>'
                u'<p>1. ポリゴンレイヤで対象ポリゴンを選択します。<br>'
                u'<img src="{select_image_path}" width="50" height="37"></p>'
                u'<p>2. 結合対象にしたいポイントレイヤを表示状態にします。</p>'
                u'<p>3. OKを押すと保存先を選び、抽出結果をQGISに追加します。</p>'
            ).format(select_image_path=select_image_path)
        )


    def run(self):
        """Run method that performs all the real work"""

        self.show_plugin_description()

        importlib.reload(merge_visible_points_in_selected_polygon)
        merge_visible_points_in_selected_polygon.run_merge_visible_points_in_selected_polygon(self.iface)
