# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WardCircleBoundary
                                 A QGIS plugin
 This plugin draws the ward boundary and a 2 km circle from a selected feature, and saves the feature as a star marker.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-15
        copyright            : (C) 2026 by Code4Construst
        email                : ubonira@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WardCircleBoundary class from file WardCircleBoundary.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ward_circle_boundary import WardCircleBoundary
    return WardCircleBoundary(iface)
